# Generated by Django 6.0 on 2025-12-15 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('session_string', models.TextField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Session',
                'verbose_name_plural': 'Telegram Sessions',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('chat_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('members_count', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='telegram_functionality.telegramsession')),
            ],
            options={
                'verbose_name': 'Telegram Chat',
                'verbose_name_plural': 'Telegram Chats',
                'unique_together': {('session', 'chat_id')},
            },
        ),
    ]
