# Generated by Django 6.0 on 2025-12-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_functionality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='last_full_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='last_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_outgoing', models.BooleanField(default=False)),
                ('has_media', models.BooleanField(default=False)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reply_to_msg_id', models.BigIntegerField(blank=True, null=True)),
                ('forwards', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_functionality.telegramchat')),
            ],
            options={
                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'ordering': ['-date'],
                'unique_together': {('chat', 'message_id')},
            },
        ),
    ]
