# Generated by Django 6.0 on 2025-12-15 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_functionality', '0002_telegramchat_is_pinned_telegramchat_last_full_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('sync_all', 'Sync All Chats'), ('sync_chat', 'Sync Single Chat'), ('check_deleted', 'Check Deleted Messages')], default='sync_all', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_chats', models.IntegerField(default=0)),
                ('synced_chats', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('synced_messages', models.IntegerField(default=0)),
                ('new_messages', models.IntegerField(default=0)),
                ('current_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('current_chat_title', models.CharField(blank=True, default='', max_length=255)),
                ('current_chat_progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='telegram_functionality.telegramsession')),
            ],
            options={
                'verbose_name': 'Sync Task',
                'verbose_name_plural': 'Sync Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
