# Generated by Django 6.0 on 2025-12-18 19:22

import telegram_functionality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_functionality', '0003_synctask'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='media_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=telegram_functionality.models.telegram_media_path),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='media_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
