# Generated by Django 6.0 on 2025-12-22 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_functionality', '0005_multi_session_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#0088cc', max_length=7)),
                ('icon', models.CharField(default='bi-folder', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Folder',
                'verbose_name_plural': 'Chat Folders',
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeletionAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_webhook', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('only_own_messages', models.BooleanField(default=False)),
                ('min_message_age_hours', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_alert_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Alert Config',
                'verbose_name_plural': 'Deletion Alert Configs',
            },
        ),
        migrations.CreateModel(
            name='KeywordAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('regex', 'Regular Expression')], default='contains', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_webhook', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('chats', models.ManyToManyField(blank=True, related_name='keyword_alerts', to='telegram_functionality.telegramchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keyword Alert',
                'verbose_name_plural': 'Keyword Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_triggers', to='telegram_functionality.telegrammessage')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='telegram_functionality.keywordalert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_text', models.TextField()),
                ('new_text', models.TextField()),
                ('edited_at', models.DateTimeField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='telegram_functionality.telegrammessage')),
            ],
            options={
                'verbose_name': 'Message Edit',
                'verbose_name_plural': 'Message Edits',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='telegram_functionality.telegrammessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Note',
                'verbose_name_plural': 'Message Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('html', 'HTML')], default='json', max_length=10)),
                ('include_media', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_backups', to='telegram_functionality.telegramsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Backup',
                'verbose_name_plural': 'Scheduled Backups',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('messages_count', models.IntegerField(default=0)),
                ('chats_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_history', to=settings.AUTH_USER_MODEL)),
                ('scheduled_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='telegram_functionality.scheduledbackup')),
            ],
            options={
                'verbose_name': 'Backup History',
                'verbose_name_plural': 'Backup History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('daily_stats', 'Daily Statistics'), ('hourly_activity', 'Hourly Activity'), ('top_senders', 'Top Senders'), ('word_frequency', 'Word Frequency'), ('media_stats', 'Media Statistics')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_cache', to='telegram_functionality.telegramsession')),
            ],
            options={
                'verbose_name': 'Analytics Cache',
                'verbose_name_plural': 'Analytics Caches',
                'unique_together': {('session', 'cache_type', 'date_from', 'date_to')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('connect_telegram', 'Connect Telegram'), ('disconnect_telegram', 'Disconnect Telegram'), ('sync_chats', 'Sync Chats'), ('sync_messages', 'Sync Messages'), ('export_data', 'Export Data'), ('delete_data', 'Delete Data'), ('create_bookmark', 'Create Bookmark'), ('delete_bookmark', 'Delete Bookmark'), ('create_tag', 'Create Tag'), ('create_folder', 'Create Folder'), ('download_media', 'Download Media'), ('view_message', 'View Message'), ('search', 'Search'), ('settings_change', 'Settings Change'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='telegram_functionality.telegramchat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='telegram_functionality.telegrammessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='telegram_functionality.telegramsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='telegram_fu_user_id_d3ca4e_idx'), models.Index(fields=['action', '-created_at'], name='telegram_fu_action_384bad_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatFolderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_memberships', to='telegram_functionality.telegramchat')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='telegram_functionality.chatfolder')),
            ],
            options={
                'unique_together': {('folder', 'chat')},
            },
        ),
        migrations.CreateModel(
            name='MediaHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('perceptual_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_hash', to='telegram_functionality.telegrammessage')),
            ],
            options={
                'verbose_name': 'Media Hash',
                'verbose_name_plural': 'Media Hashes',
                'indexes': [models.Index(fields=['file_hash'], name='telegram_fu_file_ha_d8718e_idx'), models.Index(fields=['perceptual_hash'], name='telegram_fu_percept_6bcc6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='telegram_functionality.telegrammessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.CreateModel(
            name='MessageTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='telegram_functionality.telegrammessage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_taggings', to='telegram_functionality.tag')),
            ],
            options={
                'unique_together': {('tag', 'message')},
            },
        ),
    ]
