# Generated by Django 6.0 on 2025-12-22 17:22

import django.db.models.deletion
import telegram_functionality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_functionality', '0006_chatfolder_deletionalertconfig_keywordalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_scam', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=telegram_functionality.models.user_photo_path)),
                ('photo_id', models.BigIntegerField(blank=True, null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='telegram_functionality.telegramsession')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('admin', 'Administrator'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked'), ('banned', 'Banned')], default='member', max_length=20)),
                ('admin_title', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_rights', models.JSONField(blank=True, default=dict)),
                ('is_member', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('restricted_until', models.DateTimeField(blank=True, null=True)),
                ('restriction_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='telegram_functionality.telegramchat')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='telegram_functionality.telegramuser')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='telegram_functionality.telegramuser')),
            ],
            options={
                'verbose_name': 'Chat Membership',
                'verbose_name_plural': 'Chat Memberships',
                'ordering': ['-role', 'telegram_user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['session', 'user_id'], name='telegram_fu_session_3c8935_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['username'], name='telegram_fu_usernam_9ca03a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegramuser',
            unique_together={('session', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(fields=['chat', 'role'], name='telegram_fu_chat_id_24fcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmembership',
            index=models.Index(fields=['telegram_user', 'is_member'], name='telegram_fu_telegra_50e152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmembership',
            unique_together={('telegram_user', 'chat')},
        ),
    ]
