# Generated by Django 6.0 on 2025-12-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_functionality', '0007_telegramuser_chatmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='synced_users',
            field=models.IntegerField(default=0),
        ),
    ]
